## This file is ran automatically the first time a Python program imports the package dbdemo
from flask import Flask
from flask_mysqldb import MySQL
from dbdemo.student import student
from dbdemo.grade import grade
from dbdemo.book import book
from Data.config import info_data

## __name__ is the name of the module. When running directly from python, it will be 'dbdemo'
## Outside of this module, as in run.py, it is '__main__' by default
## Create an instance of the Flask class to be used for request routing
app = Flask(__name__)

## configuration of database
app.config["MYSQL_USER"] = info_data['user']
app.config["MYSQL_PASSWORD"] = info_data['password']
app.config["MYSQL_DB"] = info_data['database']
app.config["MYSQL_HOST"] = info_data['host']
app.config["SECRET_KEY"] = 'key' ## secret key for sessions (signed cookies). Flask uses it to protect the contents of the user session against tampering.
app.config["WTF_CSRF_SECRET_KEY"] = 'key' ## token for csrf protection of forms.
## secret keys can be generated by secrets.token_hex()

## initialize database connection object
db = MySQL(app)

## routes must be imported after the app object has been initialized
from dbdemo import routes
from dbdemo.grade import routes
from dbdemo.student import routes
from dbdemo.book import routes
app.register_blueprint(student)
app.register_blueprint(grade)
app.register_blueprint(book)
